{
  "contest": 226,
  "handle": "__141345__",
  "risk": "2",
  "title": "DoS  due to external call failure",
  "issueId": 770,
  "issueUrl": "https://github.com/code-423n4/2023-03-asymmetry-findings/issues/770"
}